travis:
  secure:
    BINSTAR_TOKEN: OzFagW1rXqEYkmA1HyvCcuMZ2vLSD+L33QRq/jzUafNbkPonY8eZAnrsBKNW+Odv1fGGzo12hHG6dj1u+THIKkCRK8mOkTIbSGyOdb6ZNum7Wi0qY3yeSnBjEPi9b82MzXZdVS+0PyyCxWpVYLWV7/UqlqkV5gYOIrWj1PjRD0WVAv420/4wL2L/p8u6faHX8o/9EaNNl35SBaAsIauXJszw6gAIesFOS5aduUToixs7rGAA4ocdo9wCRVvazRgPrH3yXqP81asXpE0m9Pt8riscBIaZ5JKc1vsBmc3EXUnUUGjjapgJ/9PxuDWmpuKKiYqgBzyxJMyXzCZE16YVev222GzWD7Zvh9jDL47+tryUjQ8kS1UpXSUUAzVt8ggUajnlN6kXzsDvlOGYD+Pz/mOiO9WM/0vqo7sxD0sPO3Spt9X7B4qTUA/CzdSPPXfzXEz8YM3Cl4Hspbw+wX5HBpvxZZKCsdG6KtinJXV9Z8dlDPSRr88+07/nCsW/xA2bvwN5xB/8+S3SXrJO3M2t4UbgsX408gQw8iWM8UWJid+R8XtXXfHqvTXYz/EMZKMbHDtvtkIjUev9xT81txM/jyyOL32+aty45w7Gt0HBkFGNMOLJzm966macene8Q+W4co6R3dp9aOsJK9lpTb/Qa+GoW2XwNbZCWX0rQePOHF4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
